### ISSUE TITLE
Provide access

### ISSUE THREAD

**Issue by santanaruben** [BarnBridge/Meme-Competitions#2]
Hi, I can't access the discord channel. The link is broken or something.

**Comment by DannyDesert** [comment]
> Hi, I can't access the discord channel. The link is broken or something.

Hey @santanaruben where are you getting the broken link?

Here is a current link: https://discord.gg/GPJUtHr

**Comment by MarkWardBro** [comment]
It was in the Bounty I will fix it going forward
